import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Container from "@/components/Container";
import { AuthProvider } from "@/components/AuthProvider";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "BookLike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${inter.className} flex flex-col`}>
      <Suspense fallback={<p>Loading feed...</p>}>
          <AuthProvider>
            <Container>
              {/* <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              > */}
                {children}
              {/* </ThemeProvider> */}
            </Container>
          </AuthProvider>
      </Suspense>
        </body>
    </html>
  );
}

